include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    deprecated_member_use_from_same_package: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"

linter:
  rules:
    # Error Prevention
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - valid_regexps
    
    # Style
    - always_declare_return_types
    - annotate_overrides
    - avoid_init_to_null
    - avoid_unnecessary_containers
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - unnecessary_string_interpolations
    - unnecessary_this